
---- COMO USUARIO DAMUSER26

DROP TABLE ALUM_ASIG;
DROP TABLE PROF_ASIG;

DROP TABLE PROFESOR;
DROP TABLE ASIGNATURA;

DROP TABLE ALUMNO;  

DROP SEQUENCE ALUMNO_SEQ; 

CREATE TABLE ALUMNO(
	id INTEGER PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	apellido VARCHAR(50) NOT NULL);

CREATE SEQUENCE ALUMNO_SEQ 
    START WITH 1
    INCREMENT BY 1;

INSERT INTO ALUMNO VALUES (
    ALUMNO_SEQ.NEXTVAL,
    'JUAN',
    'GUTIERREZ');

INSERT INTO ALUMNO VALUES (
    ALUMNO_SEQ.NEXTVAL,
    'MANUEL',
    'GARCIA');

INSERT INTO ALUMNO VALUES (
    ALUMNO_SEQ.NEXTVAL,
    'MANUEL',
    'GARCIA');

INSERT INTO ALUMNO VALUES (
    ALUMNO_SEQ.NEXTVAL,
    'MANUEL',
    'GARCIA');

select * from alumno;

UPDATE alumno SET nombre='JAIME', apellido='PEREZ' WHERE id='7'

CREATE TABLE PROFESOR (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	apellido VARCHAR(50) NOT NULL );

CREATE TABLE ASIGNATURA (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	curso SMALLINT,
	ciclo VARCHAR(50));

CREATE TABLE ALUM_ASIG (
	ASIGNATURA INT,
	ALUMNO INT,
    FALTAS INT,
	PRIMARY KEY(ASIGNATURA,ALUMNO),
	FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(id) ,
	FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURA(id) );

CREATE TABLE PROF_ASIG (
	ASIGNATURA INT,
	PROFESOR INT,
    HORAS_SEMANALES INT,
	PRIMARY KEY(ASIGNATURA, PROFESOR),
	FOREIGN KEY (PROFESOR) REFERENCES PROFESOR(id),
	FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURA(id));

INSERT INTO ALUMNO VALUES (
	NULL,
	'PEPE',
	'PEREZ');
INSERT INTO PROFESOR VALUES (
	NULL,
	'JUAN',
	'GUTIERREZ');
INSERT INTO ASIGNATURA VALUES (
	NULL,
	'Acceso a Datos',
	2,
	'DAM'
);

-- INSERT INTO PROF_ASIG VALUES ();
-- INSERT INTO PROF_ASIG VALUES ();

